Repository webpack-contrib/sass-loader, pull requests merged in 2018-04, with the labels that each got.

#551 Capitalize Sass
  README.md
Labels: pr_action: Merge ready, semver: Patch, severity: 5 (confusing), type: Documentation

#533 refactor(package): remove `node-sass` (`peerDependencies`)
  .nycrc
  lib/loader.js
  package-lock.json
  package.json
  test/index.test.js
Labels: pr_action: Review, priority: 5 (nice to have), semver: Major, type: Refactor

#479 fix: respect `webpack` aliases (`resolve.alias`)
  lib/importsToResolve.js
  lib/webpackImporter.js
  test/index.test.js
  test/sass/alias.sass
  test/sass/import-alias.sass
  test/sass/import-css.sass
  test/sass/imports.sass
  test/scss/alias.scss
  test/scss/import-alias.scss
  test/scss/imports.scss
  test/tools/createSpec.js
Labels: pr_action: Review, priority: 3 (required), semver: Patch, status: Pending, type: Bug
